#!/usr/bin/env bash
# Bash script to display username, user id, and home directory path from /etc/passwd

while IFS=: read -r username _ uid _ _ home shell; do
    echo "$username:$uid:$home"
done < /etc/passwd
