#!/usr/bin/env bash
# Display numbers from 1 to 20 and show special messages for specific iterations.

count=1

while [ $count -le 20 ]; do
    if [ $count -eq 4 ]; then
        echo "4 and then bad luck from China"
    elif [ $count -eq 9 ]; then
        echo "9 and then bad luck from Japan"
    elif [ $count -eq 17 ]; then
        echo "17 and then bad luck from Italy"
    else
        echo $count
    fi
    ((count++))
done
