#!/usr/bin/env bash
# Display time for 12 hours and 59 minutes without for or until loops.

hour=0
minute=1

while [ $hour -le 12 ] && [ $minute -le 59 ]; do
    printf "%02d:%02d\n" $hour $minute
    ((minute++))
    if [ $minute -gt 59 ]; then
        ((hour++))
        minute=0
    fi
done | head -n 70
