#!/usr/bin/env bash
# Display time for 12 hours and 59 minutes using a while loop.

hour=0
minute=0
lines_to_display=70

while [ $hour -lt 13 ] && [ $minute -lt 59 ] && [ $hour -ne 12 ] || [ $minute -ne 0 ]; do
    if [ $minute -eq 0 ]; then
        printf "Hour: %d\n" $hour
    fi
    printf "%02d\n" $((++minute))
    ((minute==60)) && ((minute=0, ++hour))
done | head -n $lines_to_display
