#!/usr/bin/env bash
# Display time for 12 hours and 59 minutes without using for or until loops.

hour=0
minute=0
lines_to_display=70
count=0

while [ $count -lt $lines_to_display ]; do
    if [ $minute -eq 0 ]; then
        printf "Hour: %d\n" $hour
    fi
    printf "%02d\n" $((minute%60))
    ((minute++))
    if [ $minute -eq 60 ]; then
        ((hour++))
        minute=0
    fi
    if [ $hour -eq 12 ] && [ $minute -eq 0 ]; then
        break
    fi
    ((count++))
done
