#!/usr/bin/env bash
# Display contents of the current directory in a list format
# Only display the part of the name after the first dash

for file in *; do
    if [[ -f "$file" && ! "$file" =~ ^\. ]]; then
        name_after_dash="${file#*-}"
        echo "$name_after_dash"
    fi
done
